version: '3.2'
services:
  backend:
    build: backend
    ports:
      - 20000:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    env_file:
      - docker-compose.env
      - docker-compose.env.local

  queue:
    build: console
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app:cached
    command: queue/listen -v
    env_file:
      - docker-compose.env
      - docker-compose.env.local

  mysql:
    image: mysql:8.0
    volumes:
      - /var/lib/infotek:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=infotek
      - MYSQL_DATABASE=infotek
      - MYSQL_USER=infotek
      - MYSQL_PASSWORD=infotek
    ports:
      - "3307:3306"

  redis:
    image: redis:alpine